# Example configuration file for evolutionary txt2img.
# Intended for advanced users.

outdir: outputs/evolutionary_txt2img
min_population_for_crossbreed: 16
prompt:
  start: Skeleton laughing while vaping
  always:
    - r/creepy
  maybe:
    - abandoned hospital
    - alleyway
    - amateur photograph
    - award-winning photograph
    - big clouds of smoke
    - blood splatter
    - bones
    - cover of National Geographic
    - dark
    - evil
    - flashlight
    - forest
    - found footage
    - harsh lighting
    - horror
    - Knochen
    - lachendes Skelett
    - Lovecraft
    - night
    - r/interestingasfuck
    - r/OldSchoolCool
    - rauchendes Skelett
    - Rauchschwaden
    - red eyes
    - rot leuchtende Augen
    - scary
    - spooky
    - undead
    - unnatural
    - unnerving
    - VHS tape
ddim_steps: 50  # legacy name, applies to all algorithms.
# Adding an int to toggles enables the corresponding feature.
# 0: Create prompt matrix (separate multiple prompts using |, and get all combinations of them)
# 1: Normalize Prompt Weights (ensure sum of weights add up to 1.0)
# 2: Save individual images
# 3: Save grid
# 4: Sort samples by prompt
# 5: Write sample info files
# 6: Fix faces using GFPGAN
# 7: Upscale images using Real-ESRGAN (NOT TESTED)
toggles: [1, 2, 3, 4, 5]
sampler_name: k_lms  # Valid: DDIM, k_dpm_2_a, k_dpm_2, k_euler_a, k_euler, k_heun, k_lms
ddim_eta: 0.0
n_iter: 9
batch_size: 1
cfg_scale: 10.0
seed:
height: 512
width: 512
# The options below this line have not been tested. Use at your own discretion.
# Textual inversion embeddings file path:
fp:
realesrgan_model_name:
